# /etc/bash/bash_logout /etc/zsh/zlogout

# This file is sourced when a login shell terminates.

sync

# You may wish to clear everyone's screen when they logout.
clear

# Or maybe you want to leave a thoughtful note.
#fortune
